### ISSUE TITLE
Regaliator Java Client is not working

### ISSUE THREAD

**Issue by ovargas27** [regalii/regaliator_java#1]
Virtual Market claims Regaliator Java client is not working

**Comment by GRoguelon** [comment]
Can I have feedback on the errors they get?

**Comment by ovargas27** [comment]
@GRoguelon Jorge is reviewing it
@jdsampayo Do you know what is the error they are getting?

**Comment by jdsampayo** [comment]
There was a bug with the dates, fixed in master
